imports:
- $import torch
- $import scripts
- $import scripts.network
- $import scripts.trainer
- $import scripts.loader

network:
  _target_: scripts.network.UNET

train_val_files: '$scripts.loader.get_files(@input_dir)'
dataloader: '$scripts.loader.train_val_loader(@train_val_files, @a_min, @a_max, @iso_patch_size_tr, @voxel_space1, @voxel_space2, @voxel_space3, @posneg_sample, @n_worker, @batch_tr, @batch_val)'
learner: '$scripts.trainer.training(@max_epochs, @network, @val_interval, @dataloader, @device, @iso_patch_size_val, @sw_batch_size, @abs_path_checkpoint, @fig_save_path)'

