imports:
- "$import glob"
- "$import os"
- "$import monai"
- "$import monai.networks.layers.Norm"


network_def:
  _target_: monai.networks.nets.UNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 2
  channels:
  - 16
  - 32
  - 64
  - 128
  - 256
  strides:
  - 2
  - 2
  - 2
  - 2
  num_res_units: 2
  norm: monai.networks.layers.Norm.BATCH